kind: ReplicationController
apiVersion: v1
metadata:
  name: redis-price-master
  labels:
    app: redis-price
    role: master
spec:
  replicas: 1
  selector:
    app: redis-price
    role: master
  template:
    metadata:
      labels:
        app: redis-price
        role: master
    spec:
      containers:
      - name: redis-price-master
        image: redis:6.2-rc2-alpine
        ports:
        - name: redis-price
          containerPort: 6379